version: '3'

networks:
  commissionCalculator:
    name: commissionCalculator

services:
  nginx:
    image: nginx:stable-alpine
    container_name: "commissionCalculator_nginx"
    ports:
      - "89:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - commissionCalculator
  php:
    build:
      context: .
      dockerfile: DockerFile_php
    container_name: "commissionCalculator_php"
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - commissionCalculator
  composer:
    image: composer
    container_name: ${APP_NAME}_composer
    volumes:
      - ./:/app
    working_dir: /app
    networks:
      - commissionCalculator
    command: sh -c "composer install --ignore-platform-reqs && cp .env.example .env && php artisan key:generate"